{% set name = "pytest-github-actions-annotate-failures" %}
{% set version = "0.1.5" %}

# TODO:
# - version >0.1.0 (unreleased) includes LICENSE in sdist, remove from feedstock

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-github-actions-annotate-failures-{{ version }}.tar.gz
  sha256: 42a7e58c583f69a0a85302c04c04c060881ed170bcffcc57be2b6b8673b8a879

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ==2.7|>=3.6
  run:
    - pytest >=4.0.0
    - python ==2.7|>=3.6

test:
  imports:
    - pytest_github_actions_annotate_failures
  commands:
    - python -m pip check
  requires:
    - pip

about:
  home: https://github.com/utgwkk/pytest-github-actions-annotate-failures
  summary: pytest plugin to annotate failed tests with a workflow command for GitHub Actions
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
